spring:
  application:
    name: weibo-script
  main:
    web-environment: false
  jpa:
    show-sql: true

config:
  threadCount: 1
  userQueue: WEIBO-CLOUD-USER-QUEUE
  userResultQueue: WEIBO-CLOUD-RESULT-NEW-USER
  ipQueue: WEIBO-CLOUD-IP-QUEUE
  userRelationQueue: WEIBO-CLOUD-USER-RELATION-QUEUE
  userRelationResultQueue: WEIBO-CLOUD-RESULT-USER-RELATION-QUEUE
  maxRetryTime: 5
  datasource:
    name: weibo-mysql
    url: jdbc:mysql://222.173.119.102:3306/weibo?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: leo
    password: Xu8373616!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    validationQuery: SELECT 1